/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getPrayerTimesForCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getSelectedCity' : IDL.Func([], [IDL.Text], ['query']),
  'getTodaysHijriDate' : IDL.Func([], [IDL.Text], ['query']),
  'getUserPrayerTimes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'setSelectedCity' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getPrayerTimesForCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getSelectedCity' : IDL.Func([], [IDL.Text], ['query']),
    'getTodaysHijriDate' : IDL.Func([], [IDL.Text], ['query']),
    'getUserPrayerTimes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setSelectedCity' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };